//= require "jquery.ba-bbq.min"
//= require "jquery.slideto.min"
//= require "jquery.tmpl"
//= require "jquery.wiggle.min"
//= require "chosen.jquery"
//= require "doc"
//= require "underscore-min"
//= require "spine"